### ISSUE TITLE
etcd close(r.closeCh)

### ISSUE THREAD

**Issue by coder2z** [zzonee/registry#3]
etcd 的服务发现 这里你的 关闭是使用的 close(r.closeCh) 但是 会出现 取消操作未完全执行成功，建议使用一个wait()

**Comment by zzonee** [comment]
只要控制Register里起的协程退出即可。

**Comment by coder2z** [comment]
这里的协程的确退出了 ，但是会出现下面的key删除有可能不能执行

**Comment by zzonee** [comment]
etcd的租约到期后会自动删除key的。特殊情况下，unregister也可能不会执行，比如被kill掉。加上wait也有好处，可以避免服务发现方"迟钝"。

**Comment by coder2z** [comment]
是这样的，如果程序的最后一个defer 是 close(r.closeCh) 就会出现这个情况。建议加上，避免

**Comment by zzonee** [comment]
加上去了。不过还没有测试

**Comment by coder2z** [comment]
注册的时候 wg 没 初始化  会空指针

**Comment by zzonee** [comment]
我没用指针

**Comment by coder2z** [comment]
wg 你没初始化 使用 会painc 空指针异常

**Comment by zzonee** [comment]
我运行了测试文件，没用空指针异常。结构体直接声明就可以了，你再看一下，wg不是指针。

**Comment by coder2z** [comment]
嗷嗷 看错了 看成你wg用的指针 那应该OK
